* Remove python3.6 from dependancies in debain control, to allow local python3.6+ installs to be utilized. Fixes #22   * Include .git folder with previoud 10 commits, to allow the updater to work. Fixes #24   * Check for python3.6+ versions in system path, and update the service file to the latest found. call 'dpkg-reconfigure sickchill' if it changes to update the service   * Fix error in service where ExecStart path was not absolute. Fixes #25   * No longer copy config from /apps/sickrage automatically, this could cause a data overwrite if users used the other repo.
Signed-off-by: miigotu <miigotu@gmail.com>

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,9 +21,11 @@ set -e
 case "$1" in
     configure)
         chown -R admin:admin /apps/sickchill
-        if [ -d "/apps/sickrage/app-config/" ] && [ ! -f /apps/sickchill/app-config/config.ini ]; then
-            cp -r /apps/sickrage/app-config/* /apps/sickchill/app-config/
-        fi
+        SC_PYTHON=$(command -v python3.9 || command -v python3.8 || command -v python3.7 || command -v python3.6)
+        [ -z $SC_PYTHON ] && (echo "Python 3.6+ not found in your path. After fixing this issue, call 'dpkg-reconfigure sickchill'" && exit 1)
+        echo "Found python3 at $SC_PYTHON, setting service to use this interpreter"
+        echo "If you change python versions or path, call 'dpkg-reconfigure sickchill' to fix the service"
+        sed -i "s#ExecStart=.* /apps/sickchill/SickChill.py#ExecStart=$SC_PYTHON /apps/sickchill/SickChill.py#g" /apps/sickchill/fvapp-sickchill.service
         ;;
     abort-upgrade|abort-remove|abort-deconfigure)
     ;;
